### DISCUSSION TITLE
Vela with Docker Compose

### DISCUSSION THREAD

**Discussion by dR3b** [go-vela/community#750] [General] [answered]
I always get the same error when I try to start Vela with Docker:

```
vela-server  | {"level":"fatal","msg":"no scm client id provided","time":"2023-02-21T09:28:07Z"}
vela-server exited with code 1
```

This is my `docker-compose.yml` file:

```
version: "3.9"
networks:
  vela:
    external: false
services:
  server:
    container_name: vela-server
    image: target/vela-server:v0.17.0-alpine
    init: true
    restart: always
    environment:
      # DATABASE_DRIVER: postgres
      # DATABASE_ADDR: 'postgres://vela:zB7mrKDTZqNeNTD8z47yG4DHywspAh@postgres:5432/vela?sslmode=disable'
      # DATABASE_COMPRESSION_LEVEL: 3
      DATABASE_ENCRYPTION_KEY: 'C639A572E14D5075C526FDDD43E4ECF6'
      QUEUE_DRIVER: 'redis'
      QUEUE_ADDR: 'redis://redis:6379'
      # SECRET_VAULT: 'true'
      # SECRET_VAULT_ADDR: 'http://vault:8200'
      # SECRET_VAULT_TOKEN: 'vela'
      VELA_ADDR: 'http://localhost:8080'
      VELA_WEBUI_ADDR: 'http://localhost:8888'
      VELA_LOG_LEVEL: 'trace'
      VELA_SECRET: 'zB7mrKDTZqNeNTD8z47yG4DHywspAh'
      VELA_REFRESH_TOKEN_DURATION: 90m
      VELA_ACCESS_TOKEN_DURATION: 60m
      VELA_DISABLE_WEBHOOK_VALIDATION: 'true'
      VELA_ENABLE_SECURE_COOKIE: 'false'
    networks:
      - vela
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    container_name: vela-redis
    image: redis:7-alpine
    init: true
    restart: always
    networks:
      - vela
    ports:
      - "6379:6379"
```
Any ideas? What am I doing wrong?
