### ISSUE TITLE
server/ui: support typed deployment parameters with dynamic forms

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#1002]
## Description

support a better process for creating deployments.

the idea is to have yaml keys that define how a dynamic form should render in the UI.

```yaml
deployment:
  inputs:
    region:
      type: string
      description: which fake region to deploy to
      default: east
    options:
      type: stringarray
      description: some list of string options
      default: [ foo, bar ]
```

Spinnaker screenshot for inspiration:
![image](https://github.com/user-attachments/assets/66b1bf52-8a64-4eb0-b61d-b1997325fd76)
