### ISSUE TITLE
init step logs spills into subsequent step

### ISSUE THREAD

**Issue by wass3rw3rk** [go-vela/community#1013]
## Description

In certain scenarios it is possible for the `init` step logs to be prepended to a subsequent step's logs erroneously. Using the pipeline below, you will see that the `clone` step logs will start out with the `init` step logs' content.

## Value

Log should be properly captured in all scenarios.

## Useful Information

pipeline to reproduce:

`.vela.yml`
```yaml
version: "1"

steps:
  - name: echo
    image: alpine:latest
    commands:
      - echo hello

secrets:
  - origin:
      name: vault one
      image: alpine:latest
      parameters:
        log.level: trace
  - origin:
      name: vault two
      image: alpine:latest
      parameters:
        log.level: trace
```

Secrets plugin is faked here for ease of testing. This will reproduce the issue 100% of the time in my testing. Check `clone` step log to see the issue.

A scenario we have seen this in is when folks use multiple templates and multiple are using the secret plugin.

1. What is the output of `vela --version`?

`<= v0.25.x`

2. What operating system is being used?

3. Any other important details?
