### ISSUE TITLE
Improve the image pull options for resources

### ISSUE THREAD

**Issue by kneal** [go-vela/community#104]
## Description

Users need the ability to publish then pull docker images in a single build. We should look at creating a new pull policy that can adapt to the need for more control of when/how workers pull images.

## Value

Allows Vela users more control when spinning up images

## Definition of Done

The proposal is approved and implementation completed

## Effort  (Optional)

TBD

## Impacted Personas (Optional)

Vela users using `pull: true` in pipelines

**Comment by jbrockopp** [comment]
A pipeline has been created internally to Target and is testing very successfully 👍 

Here is the pipeline:

```
version: "1"

steps:
  - name: pull empty
    image: alpine:3.12
    commands:
      - echo "pull empty"

  - name: pull always
    image: alpine:3.11
    pull: always
    commands:
      - echo "pull always"

  - name: pull not present
    image: alpine:3.10
    pull: not_present
    commands:
      - echo "pull not present"

  - name: pull on_start
    image: alpine:3.9
    pull: on_start
    commands:
      - echo "pull on start"

  - name: pull never
    image: alpine:3.12
    pull: never
    commands:
      - echo "pull never"

  - name: deprecated pull true
    image: alpine:3.8
    pull: true
    commands:
      - echo "deprecated pull true"

  - name: deprecated pull true string
    image: alpine:3.7
    pull: "true"
    commands:
      - echo "deprecated pull true as string"

  - name: deprecated pull false
    image: alpine:3.6
    pull: false
    commands:
      - echo "deprecated pull false"

  - name: deprecated pull false string
    image: alpine:3.5
    pull: "false"
    commands:
      - echo "deprecated pull false as string"
```
