### ISSUE TITLE
ruleset: path: steps are being skipped

### ISSUE THREAD

**Issue by KellyMerrick** [go-vela/community#108]
## Description

v0.5.1 - steps with ruleset: path: are being skipped. this bug is causing previously working steps to now fail.

``` 
 - name: echo
    image: alpine:latest
    commands:
      - echo "the readme was changed"
    ruleset:
      path: ["README.md"]
```

![image](https://user-images.githubusercontent.com/31659837/90924559-530a6f80-e3b5-11ea-9575-b0519a085f69.png)

## Value

- resolve user experience to what it was prior to the bug being introduced

## Useful Information

1. What is the output of `vela --version`?

v0.5.4 (cli)
v0.5.1 (server)

2. What operating system is being used?

linux

3. Any other important details?

the worker does not have a concept of path to evaluate.
