### ISSUE TITLE
Fail a step when referencing non-existent secrets

### ISSUE THREAD

**Issue by davidvader** [go-vela/community#114]
## Description

Proposing an enhancement to steps to fail/kill a step that references a secret that has not been injected properly.

## Value

Improve the experience for users that are new to the platform.

## Definition of Done

Referencing a secret that has not been injected into the pipeline should kill that step.

## Steps to Reproduce

```yaml
version: "1"
steps:
  - name: bad-reference
    image: golang
    secrets: [ example_secret ]
    commands:
      - echo "this step contains a secret that has not been injected"
```
