### ISSUE TITLE
pull_request step using a comment trigger term didn't run the step

### ISSUE THREAD

**Issue by BertCC** [go-vela/community#118]
## Description

* Ran a pipeline for a commented trigger term of "vela-test", but that step is skipped.
* Expected the step with the trigger term to run.
* Steps to reproduce:
1) Create a vela file named .vela.yml with the following:
```
version: "1"

metadata:
  template: false
  
steps:
  - name: pull-and-check-k6-code
    image: docker.target.com/vela-plugins/git:1
    pull: true
    ruleset:
      event: [ comment ]
      comment: [ "vela-test" ]
    commands:
      - git clone -b my_k6 https://somegitcode.git
```

* Please let me know if you need additional information.

2) Create a pull request in GitHub via GitHub UI
3) Add in a comment of "vela-test"
4) The Vela pipeline runs the usual init, clone, and the "pull-and-check-k6-code" steps.
But for the last step, it just gets the skip message

## Value

* Want to use a trigger term to run tests as needed for a pipeline.  Able to do a workaround right now by using a path file change to trigger parts of a pipeline.
* No impact to security noted.

## Useful Information

1. What is the output of `vela --version`?
0.3.0
