### ISSUE TITLE
Fix logs are getting truncated

### ISSUE THREAD

**Issue by kneal** [go-vela/community#128]
## Description

Users have observed that the last message outputted in a step sometimes gets truncated and is not shipped to the server.

## Value

The full log is available to users within the server

## Useful Information

Example pipeline that can be used to test behavior:

```
version: "1"

steps:
  - name: view message
    image: alpine:latest
    pull: always
    commands:
      - "[ -s /vela/secrets/hello ] || echo \"file is empty\""
      - cat /vela/secrets/hello
      - sleep 2
              
secrets:
  - name: vault_username
  - name: vault_password
  - origin:
      name: vault secrets
      image: target/vela/secret-vault:latest
      pull: always
      secrets: [ vault_username, vault_password ]
      parameters:
        log_level: trace
        items:
          - source: secret/vela/hello
            path: single
```

**Comment by jbrockopp** [comment]
I began exploring this today 👍 

First, I'll provide some links to resources that are worth mentioning in the context of this issue:

* https://github.com/moby/moby/issues/31058
* https://stackoverflow.com/questions/40389137/multiple-docker-container-logs
* https://jaxenter.com/docker-logging-gotchas-137049.html

I approached it how I normally approach bugs by reproducing it first on my local workstation.

The pipeline I used to reproduce this issue is the same as what was provided in the initial message of this issue. The only caveat is that I had to comment out the line containing `- sleep 2` otherwise I always saw the log content render properly.

```yaml
version: "1"

steps:
  - name: view message
    image: alpine:latest
    pull: always
    commands:
      - "[ -s /vela/secrets/hello ] || echo \"file is empty\""
      - cat /vela/secrets/hello
    # I had to remove this line because the output from the above `cat` command was always displaying
    # - sleep 2 
              
secrets:
  - name: vault_username
  - name: vault_password

  - origin:
      name: vault secrets
      image: target/vela/secret-vault:latest
      pull: always
      secrets: [ vault_username, vault_password ]
      parameters:
        log_level: trace
        items:
          - source: secret/vela/hello
            path: single
```
