### ISSUE TITLE
Missing secret causes the worker to crash

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#133]
## Description

Utilizing a missing secret will cause the worker process to crash instead of handling the failure gracefully. You can submit a `.vela.yml` like the one bellow to reproduce the failure:

```yaml
version: "1"

steps:
  - name: test
    image: alpine:latest
    secrets: [ password ]
    commands:
      - env 
    ruleset:
      event: [ pull_request ]
      branch: [ test ] 

secrets:
  - name: password
    engine: vault
    key: foo/bar/star
    type: shared
```

The logs I obtained from the worker are as follows:

```json
{"build":8,"host":"db2942443d93","level":"error","msg":"unable to destroy step: Error: No such container: step_JordanSussman_vela-sample_8_test","repo":"JordanSussman/vela-sample","time":"2020-10-16T14:08:15Z","user":"JordanSussman"}
{"build":8,"host":"db2942443d93","level":"info","msg":"deleting volume","repo":"JordanSussman/vela-sample","time":"2020-10-16T14:08:15Z","user":"JordanSussman"}
{"level":"trace","msg":"removing volume for pipeline JordanSussman_vela-sample_8","time":"2020-10-16T14:08:15Z"}
{"build":8,"host":"db2942443d93","level":"info","msg":"deleting network","repo":"JordanSussman/vela-sample","time":"2020-10-16T14:08:15Z","user":"JordanSussman"}
{"level":"trace","msg":"removing network for pipeline JordanSussman_vela-sample_8","time":"2020-10-16T14:08:15Z"}
{"level":"error","msg":"failing worker executor: unable to pull secrets: unable to retrieve secret: unable to get secret shared/foo/bar/star from vault service: secret secret/data/shared/foo/bar/star does not exist","time":"2020-10-16T14:08:15Z"}
{"level":"error","msg":"failing worker operator: unable to pull secrets: unable to retrieve secret: unable to get secret shared/foo/bar/star from vault service: secret secret/data/shared/foo/bar/star does not exist","time":"2020-10-16T14:08:15Z"}
{"level":"fatal","msg":"shutting down worker","time":"2020-10-16T14:08:15Z"}
```

## Useful Information

1. What is the output of `vela --version`?

0.6.0

2. What operating system is being used?

Linux

3. Any other important details?
