### ISSUE TITLE
fix JSON schema false positive with using continue in a ruleset

### ISSUE THREAD

**Issue by kneal** [go-vela/community#157]
## Description

The JSON schema is showing a false positive within a ruleset when using the `continue` syntax within a ruleset.

## Value

Convey to the user that the syntax is actually correct

## Useful Information

This shows as invalid but is actually valid

```yaml
        ruleset:
          continue: true
          branch: main
          event: [pull_request]  
```

This can explicit syntax can be used to make the error go away:

```yaml
        ruleset:
          continue: true
          if:
            branch: main
            event: [pull_request]  
```

1. What is the output of `vela --version`?

N/A

2. What operating system is being used?

N/A

3. Any other important details?

N/A
