### ISSUE TITLE
Injecting repo secrets without keys causing error

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#158]
## Description

Renaming secrets with special characters during pipeline injection causes `error: invalid secret path`.

When pulling repo secrets into a pipeline, when the name provided contains special characters and does not match the name of the secret in the database, builds will fail with `error: invalid secret path`

It is possible other secret types are impacted. 

## Value

This bug harms the platform's barrier to entry by making it difficult to track down why the repo secret path is invalid.

## Steps to Reproduce

cli
```bash
$ vela add secret --secret.type repo --org someorg --repo somerepo --name some_name --value whatever
```

```yaml
version: "1"
steps:
  - name: test
    image: golang
    commands:
      - echo "hello" 
secrets:
  - name: name_with_underscores
    key:  some_name
    engine: native
    type: repo
```

## Additional Information

Matching the name provided with the actual name of the secret will succeed, even if the name contains special characters like underscores
```yaml
secrets:
  - name: some_name
    key:  some_name
    engine: native
    type: repo
```

While changing the name will cause an error ``
```yaml
secrets:
  - name: some_other_name
    key:  some_name
    engine: native
    type: repo
```

**Comment by wass3r** [comment]
Looks like it's explicitly checking for the name and key to match here if you're using the implicit version:
https://github.com/go-vela/types/blob/dc6c041aeb84ae1e3aa53dd8e07e539f553a5ea0/pipeline/secret.go#L169-L171

I don't think it's necessary?! @kneal , was there a specific reason for that check?

**Comment by kneal** [comment]
Yeah, the name and the key need to match for an implicit secret to be derived from the most basic syntax. Basically if a user has:

```yaml
steps:
- name: foo
  secrets: [ foo ]
  commands: [ "echo $FOO" ]

secrets:
  - name: foo
```

Behind the scenes, the name and key are now the same and implicit. So we need to populate the secret fields of the struct accordingly. A lot of the secret syntax checking could be simplified or removed if we didn't support `repo` type secrets in an implicit format. Sadly, we do so we have enhanced checking for those cases.
