### ISSUE TITLE
Enhance ruleset event support

### ISSUE THREAD

**Issue by NaromKuoch** [go-vela/community#159]
## Description

* Proposing adding a support for additional `event` in `ruleset`. 
* For example, there are no support when editing an existing PR.  

Scenario: 
By default when opening a PR it'll target our default branch (main) and if somebody is aiming to cherry-pick their PR into the release branch they'll edit the PR to retarget the new base branch.  In this case, there is no build that gets triggered because Vela only supports few events including `pull_request`, `commnent`, `tags`, `push`, etc.

What I would be imagining is that anything that is "action": "edited" triggers a rebuild.

## Value

This is important because in the worst scenarios, the stale-ness of the checks means that bad commits make it into the repo based on some merge commit from a branch other than what it would move into.

## Definition of Done

* The expected results is when editing existing PR, the user has an ability to configure Vela so that build can get triggered.
* Documentations needs to be edited for additional events to support.

**Comment by wass3r** [comment]
I have a use-case for this as well. For pull request alone there are a number of (sub) events we could support.

refs:
https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/github-event-types#pullrequestevent 
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request

**Comment by NaromKuoch** [comment]
Adding an additional request for PR approval event.  
There is a use-case where we would like to trigger a build when PR is approved.

refs:
- https://docs.github.com/en/developers/webhooks-and-events/github-event-types#pullrequestreviewevent

**Comment by ecrupper** [comment]
Given some of the feedback on [the initial types PR](https://github.com/go-vela/types/pull/233), I think it would be a good idea to discuss overall implementation of this feature in greater depth. 

#### YAML Ideas

With the inclusion of more events, many of them sub-events, we have to consider how this will affect the pipeline writing for our end users. I have a few markups for how this might work, which hopefully will generate some discussion as to which direction we want to take.

##### Mark Up 1 (putting sub-events on same level as normal events)
```yaml
steps:
    - name: original behavior
      ruleset:
          event: [push, pull_request]
    
    - name: original behavior using sub-events
      ruleset:
          event: [push, pr_open, pr_commit]

    - name: example customized event set
      ruleset:
          event: [push, pr_edit, pr_label]
          label: bug
```

##### Mark Up 2 (scoping sub-events of PRs)
```yaml
steps:
    - name: original behavior using scoping
      ruleset:
          event: [push, pull_request:open, pull_request:commit]

    - name: example customized event set
      ruleset:
          event: [push, pull_request:edit, pull_request:label]
          label: bug
```

##### Mark Up 3 (unrolling events array into a YAML structure like `steps`)
```yaml
steps:
    - name: original behavior using yaml structuring
      ruleset:
          events: 
              - type: push
              - type: pull_request
                actions: [open, commit]

    - name: example customized event set
      ruleset:
          events:
              - type: push
              - type: pull_request
                actions: [edit, label]
                label: bug
```
