### ISSUE TITLE
VELA_BUILD_STATUS returns `pending` on build success/failure

### ISSUE THREAD

**Issue by kennyli92** [go-vela/community#169]
## Description

The environment variable `VELA_BUILD_STATUS` is currently only returning `pending` despite a build success/failure.

## Value

This variable is important for metric tracking purposes

**Comment by ecrupper** [comment]
Gave this a couple tests with the latest version of Vela `v0.20.3`, and it appears this has been resolved.

```yaml
version: "1"

steps:
    - name: hello
      image: alpine:latest
      commands:
        - echo hello
    
    - name: status
      image: alpine:latest
      commands:
        - echo $VELA_BUILD_STATUS # prints "running"
```

and 

```yaml
version: "1"

steps:
    - name: fail
      image: alpine:latest
      commands:
        - exit 1
    
    - name: status
      image: alpine:latest
      ruleset:
          status: failure
      commands:
        - echo $VELA_BUILD_STATUS # prints "failure"
```

Closing. Feel free to reopen if you experience unexpected behavior!
