### ISSUE TITLE
Edit schema to error on mixed usage of array and object

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#170]
## Description

```yaml
secrets:
  - secret1
  - source: secret2
    target: other
```

will currently pass the schema validation although it causes a build error. the schema validates that each value is of one or the other type and not that the array contains items of one type.

## Value

Help prevent users from crafting non-working pipelines.

## Useful Information

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?
