### ISSUE TITLE
Template default branch functionality broken

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#211]
## Description

The enhancement introduced in https://github.com/go-vela/community/issues/134 is actually not working as intended. It is currently taking the invoking repo's default branch and using that to infer the branch of a referenced template in a different repo when the branch is not defined. For example,

## Repo A
pipeline-repo (default branch: main)
- .vela.yml with the following defined:
  ```yaml
  templates:
    - name: example
      source: github.com/my-org/template-repo/template.yml
      type: github
  ```

## Repo B
template-repo (default branch: template)
- template.yml

In the above scenario, since the `source` doesn't define a branch via `@<branch>`, the current implementation will use the invoking repo's default branch, `main` in this case, and set that as the default branch for the template source 🤕 

## Value

The enhancement should work as intended in instances where the branch is not defined on the source reference.

## Useful Information

The workaround is to apply the branch specifier.
