### ISSUE TITLE
Return useful message when template source is invalid

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#221]
## Description

Currently, utilizing invalid template sources results in the GitHub webhook returning a 500 error without any valid reason. We should instead return some relevant error message that notes the download was unsuccessful.

## Value

Users are able to more easily debug why templates are failing.

## Definition of Done

400 error returned when template utilizes invalid/inaccessible source.

## Steps to reproduce

1. Active Vela repo
2. Add `.vela.yml` with the following content:

```yaml
version: "1"
templates:
  - name: foo
    source: foo/bar
    format: go
    type: github

steps:
  - name: foo
    template:
      name: foo
```

3. Note how the recent webhook returned by Vela has 500 error with no body

## Effort  (Optional)

1 hour

## Impacted Personas (Optional)

Users of templates.
