### ISSUE TITLE
Cache plugin rebuilds files in multiple locations

### ISSUE THREAD

**Issue by matt-fevold** [go-vela/community#262]
## Description

https://go-vela.github.io/docs/plugins/registry/pipeline/s3_cache/

when running a rebuild cache step the plugin creates files at both the original location as well as the project root. Normally this isn't an issue, but when there are duplicate names in directories (such as `.gitignore`) the rebuild will fail.

If I take a project that has this structure
```
README.md
/cacheme
--> file_to_cache2.txt
--> other_file_to_cache2.txt

/other_cacheme
--> file_to_cache.txt
--> other_file_to_cache.txt
```

Then run it through the rebuild process and `ls -R` to see the results, we're left with the following output from Vela

```
$ ls -R
--
2 | .:
3 | README.md
4 | cacheme
5 | file_to_cache.txt
6 | file_to_cache2.txt
7 | other_cacheme
8 | other_file_to_cache.txt
9 | other_file_to_cache2.txt
10 | 
11 | ./cacheme:
12 | file_to_cache2.txt
13 | other_file_to_cache2.txt
14 | 
15 | ./other_cacheme:
16 | file_to_cache.txt
17 | other_file_to_cache.txt

```

which shows that the files exist both under their original location and the project root.

## Useful Information

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?

**Comment by matt-fevold** [comment]
For whenever this gets looked at, the `archiver` seems to be pretty simple and I would look there first.
https://github.com/go-vela/vela-s3-cache/blob/ce54ed96f003d22d672ad9ed0ae6453eb65df261/cmd/vela-s3-cache/restore.go#L74

https://github.com/go-vela/vela-s3-cache/blob/ce54ed96f003d22d672ad9ed0ae6453eb65df261/cmd/vela-s3-cache/rebuild.go#L53

https://github.com/mholt/archiver/blob/074da64920d3c1188f608a92eceb61e83b31317b/tar.go#L83

**Comment by JordanSussman** [comment]
@matt-fevold can you clarify what the `.vela.yml` looked like to produce this behavior?

**Comment by matt-fevold** [comment]
> @matt-fevold can you clarify what the `.vela.yml` looked like to produce this behavior?

Yea should have included it originally. I was able to track it down. Something like:

```
# instructs Vela which syntax version we're using
version: "1"

# instructs Vela that we are going to create a steps pipeline
steps:
  - name: rebuild_cache
    image: /vela-plugins/s3-cache:v0.5.1-1
    pull: not_present
    parameters:
      action: rebuild
      mount:
        - cacheme/file_to_cache.txt
        - cacheme/other_file_to_cache2.txt
        - other_cacheme/file_to_cache.txt
        - other_cacheme/other_file_to_cache.txt
    secrets: [cache_s3_server, cache_s3_access_key, cache_s3_secret_key]

  - name: delete_cachme_dir
    image: alpine:latest
    commands:
      - rm -rf cachme 
      - rm -rf other_cachme 
      
  - name: restore_cache
    image: ./vela-plugins/s3-cache:v0.5.1-1
    pull: not_present
    parameters:
      action: restore
    secrets: [cache_s3_server, cache_s3_access_key, cache_s3_secret_key]

  - name: validate
    image: alpine:latest
    commands:
      - ls -R
    
```
