### ISSUE TITLE
The ability to rename vault secrets' keys

### ISSUE THREAD

**Issue by benzvan** [go-vela/community#265]
## Description

The vault plugin currently writes the values of secrets to files named after the keys of secrets. I would like to be able to override the name of the keys/files in the configuration.

Example configuration:
```
secrets:
  - origin:
      name: vault
      image: target/vela/secret-vault:latest
      parameters:
        addr: vault.company.com
        token: superSecretVaultToken
        auth_method: token
        items:
          # Written to path: "/vela/secrets/docker/<key>"
          - source: secret/vela/username
            path: docker
            ## New options here (unchanged behavior if null)
            keys:
              - source: my_key
                target: renamed_key
```

## Value

When storing keys in vault, I would like to be able to re-use keys in different plugins that may have different requirements for the names of the key file.

Optional: It's possible I may only need one of the keys stored in a secret.

## Definition of Done

Given I have one or more key/value pairs stored in a secret in vault
When I use that secret in vela
Then I can have an arbitrary file name for each value in the secret.

## Effort  (Optional)

This looks like a minimal enhancement of 1-2 days max

## Impacted Personas (Optional)

Vela users consuming secrets from vault
