### ISSUE TITLE
Allow templates to access the template name

### ISSUE THREAD

**Issue by dan-kirberger** [go-vela/community#284]
## Description

When running detached steps inside a template, the step name is always prefixed with the name of the template in the originating repo. This makes it awkward to consistently refer to detached steps by hostname within the template, as the hostname is based on an arbitrary name in the build repo.

For example:
You have a repo referencing a template like this:
```
steps:
  - name: run
    template:
      name: spark-vela-template
```

And a template with a detached step like this:
```
    - name: mongo
       image: mongo:4.1
       commands:
          - mongod --replSet "rs0" --bind_ip "*"  --fork --logpath mongod.log
          - "mongo --port 27017 -eval \'rs.initiate( { _id: \"rs0\",members: [{_id: 0,host: \"mongo:27017\"}]} )\'"
          - tail -f mongod.log
       detach: true
```

Normally, other steps could contact this mongo instance via the hostname `mongo` (the name of the step), but since its running in a template, it will be prefixed with `run`, which is the arbitrary name given to it in the repo.

In this case, the template might haev another step with a hardcoded configuration to connect to mongo at hostname `run_mongo`, but that `run_` may vary depending on outside config, without our knowledge.

## Value

More consistent template behavior. right now it relies on users referencing templates a specific way, the `name` field, which otherwise has no specific meaning to users in the repo, suddenly becomes important.

**Comment by JordanSussman** [comment]
Would you be happy if [platform vars](https://go-vela.github.io/docs/templates/tutorials/go/vars_platform/#examples) was extended to include the template name? I'm thinking about something the following configuration:

```yaml
version: "1"
templates:
  - name: sample
    source: github.com/<org>/<repo>/path/to/file/<template>.yml
    type: github

steps:
  - name: sample
    template:
      name: echo
```

```yaml
metadata:
  template: true

steps:
  - name: test
    commands:
      - echo {{ vela "VELA_TEMPLATE_NAME" }}
    image: alpine
    pull: always
    ruleset:
      event: [ push, pull_request ]
```

Which would return: 

```yaml
version: "1"
steps:
  - name: sample_echo
    commands:
      - echo sample
    image: alpine
    pull: always
    ruleset:
      event: [ push, pull_request ]
```
