### ISSUE TITLE
Support variable substitution within secrets

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#298]
## Description

The ability to utilize variable substation within the `secrets` tag. Example:

```yaml
secrets:
- name: FOO
  key: ${VELA_REPO_ORG}/FOO
  engine: native
  type: org
- name: BAR
  key: ${VELA_REPO_ORG}/BAR
  engine: native
  type: org
```

## Value

Users are able to reduce some hardcoded reference within secrets.

## Definition of Done

Variable substitution works for all sections of the `secrets` tag.

## Effort  (Optional)

1 day

## Impacted Personas (Optional)

All users of secrets.
