### ISSUE TITLE
BUILD_LINK often points to previous build

### ISSUE THREAD

**Issue by meinenec** [go-vela/community#322]
## Description

The `BUILD_LINK` env var often points to the previous build rather than the current build. To replicate, you can run a simple step like:
```
  - name: check_build
    image: alpine:latest
    commands:
      - echo $BUILD_LINK
      - echo $BUILD_NUMBER
```

This doesn't happen 100% of the time, but in my testing occurred well over 50% of the time running on a worker with a single executor.

## Value

users often use $BUILD_LINK in slack alerts so if it links to the wrong build it may lead to confusion.
