### ISSUE TITLE
artifactory plugin path parameter bug

### ISSUE THREAD

**Issue by GregoryDosh** [go-vela/community#324]
## Description
Malformed path parameters can cause the plugin to fail to create directories and instead leaves Artifactory in a state where a directory is actually the most recently uploaded file which is probably unintended behavior.

A contrived simple example such as
```yaml
  - name: artifactory upload
    image: target/vela-artifactory
    ruleset:
      branch: main
      event: push
    secrets: [ artifactory_username, artifactory_password ]
    parameters:
      path: |
        groyalmoney/vela-test/1/
        
      action: upload
      sources:
        - test/*.jar
        - test/*.pom
```
can trigger this behavior. Normally users wouldn't set a path like that, but that is what is kind of happening when users set the param using the `echo "groyalmoney/vela-test/1/" > /vela/parameters/artifactory/path` nomenclature. It's hard to see, but in the screenshot below that `1` shouldn't be a file, and instead should be a directory. This bug can be triggered unintentionally by users not using a `echo -n` when setting that via a special file.

![Screen Shot 2021-07-09 at 1 52 08 PM](https://user-images.githubusercontent.com/6432753/125124531-d8763b80-e0bd-11eb-8ffa-84b6ac3780c9.png)

## Value
Because the path parameter is often set using things like `echo "SOMETHING" > /vela/parameters/artifactory/path` the plugin will be getting a malformed path fairly often.

The path parameter inside the plugin should ideally strip all new lines out of any destination upload paths so that it doesn't impact end users. This bug isn't necessarily the problem w/ the plugin, and probably lies upstream in either the Jfrog go library, or the artifactory API itself. But we could fix that easily here by sanitizing the input path and then file an upstream bug.
