### ISSUE TITLE
ambiguous missing template error

### ISSUE THREAD

**Issue by GregoryDosh** [go-vela/community#327]
## Description
If a .vela.yml file defines the use of a template, but the template isn't actually anywhere available, the error in the Vela UI is ambiguous on what is happening. The UI reports `invalid reference format` which doesn't narrow down to the fact that the template is missing.

Minimal example to reproduce this behavior:
```yaml
version: "1"

steps:
  - name: some-step
    template:
      name: this_template_isnt_defined
      vars:
        some: var
```

UI Demonstration
![Screen Shot 2021-07-13 at 12 54 03 PM](https://user-images.githubusercontent.com/6432753/125501527-21e4d3d3-93da-4948-9f23-3412eff374f6.png)
