### ISSUE TITLE
vela exec pipeline loads all host environmental variables into pipeline

### ISSUE THREAD

**Issue by zapplebee** [go-vela/community#340]
## Description

With this .vela.yml
```
version: "1"
steps:
- name: see-env
  image: python:alpine
  commands:
  - printenv
```
Running `vela exec pipeline` will print all of the host's environmental variables.

## Value

This makes running community plugins, and frankly any plugins unsafe.

## Useful Information

1. What is the output of `vela --version`?

vela version v0.7.4

2. What operating system is being used?

MacOS Catalina 10.15.7
3. Any other important details?

n/a
