### ISSUE TITLE
Add `environment:` to stage

### ISSUE THREAD

**Issue by cognifloyd** [go-vela/community#420]
## Description

In the vela YAML, allow pipeline authors to define `environment` for a stage (ie to be added to the environment of each stop in the stage).

## Value

This will reduce duplication when many steps need similar environment vars.
Though global `environment` could be used, that would share the vars across stages, where each stage might need stage-specific vars.

## Definition of Done

YAML like this should be allowed:
```yaml
environment:
  HELLO: world
stages:
  lint-stage:
    environment:
      THE_ANSWER: 42
    steps:
      - name: lint step one
  test-stage:
    environment:
      THE_ANSWER: to life...
      FANCY_VAR: value
    steps:
      - name: test step one
      - name: test step two
        environment:
          FANCY_VAR: overridden
      - name: test step three
        template:
          name: my-template
templates:
  - name: my-template
    source: github.com/go-vela/templates/example.yml
    type: github
```

The resulting steps should have these environment vars:
```yaml
lint-stage.lint step one:
  HELLO: world
  THE_ANSWER: 42
test-stage.test step one:
  HELLO: world
  THE_ANSWER: to life...
  FANCY_VAR: value
test-stage.test step two:
  HELLO: world
  THE_ANSWER: to life...
  FANCY_VAR: overridden
test-stage.test step three: # templated step
  HELLO: world
  THE_ANSWER: to life...
  FANCY_VAR: value
  # any vars added by the template
```

So, when adding environment vars to a step container, they should be added in this order (later overrides earlier):
1. global
2. stage
3. step

Care needs to be taken so that the stage-level vars _also_ apply to steps injected by templates.

## Effort  (Optional)

1 day

## Impacted Personas (Optional)

pipeline authors
