### ISSUE TITLE
Allow stages to be configured to run steps concurrently

### ISSUE THREAD

**Issue by JayCeeJr** [go-vela/community#421]
## Description

It would be awesome to configure stages to run steps concurrently. I would like to suggest adding a flag to stages to allow steps to be run concurrently.

i.e.
```yaml
stages:
  build:
    mode: sequential # default
    steps:
      ...
  test:
    needs: [ build ]
    mode: concurrent
    steps:
      ...
```

## Value

We have a set of integration tests that run concurrently in drone. They take around 5-10 minutes each which add up fast, and they have no dependency on each other.

The current way we could accomplish this with vela is make a bunch of stages with the same needs block. This will make the .vela.yml large and messy.

## Definition of Done

A stage will run the steps concurrently when configured to do so.
