### ISSUE TITLE
fix connection timeouts when streaming logs

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#427]
## Description

Based off of the [log streaming proposal](/https://github.com/go-vela/community/blob/master/proposals/2021/07-22_log-streaming.md)

Related to https://github.com/go-vela/community/issues/366, https://github.com/go-vela/community/issues/367, https://github.com/go-vela/community/issues/368 and https://github.com/go-vela/community/issues/369

Currently, when running the [go-vela/server](https://github.com/go-vela/server) behind a load balancer you may experiences issues when streaming logs.

Thus far, the reason for this appears to be the load balancer terminating a connection if it's idle.

Typically, load balancers will have some threshold as a timeout for any connections sending/receiving data.

If no data has been sent/received by the time the idle timeout period elapses, the load balancer closes the connection.

Here is a sample pipeline used to reproduce the issue:

> NOTE: This pipeline assumes the idle connection timeout set for the load balancer is `60s`.

```yaml
version: "1"

steps:
  - name: sleep
    image: alpine:latest
    commands:
      - sleep 65
      - echo "65 seconds"
      - sleep 65
      - echo "65 seconds v2"
      - sleep 65
      - echo "65 seconds v3"
      - sleep 65
      - echo "65 seconds v4"
      - sleep 65
      - echo "65 seconds v5"
```

The end behavior presented is the first `sleep 65` statement executes on the [go-vela/worker](https://github.com/go-vela/worker).

However, the `echo` and other `sleep` statements do not show up in the log output until the step is complete.

## Value

Prevent issues with log streaming for architectures that use Vela behind a load balancer

## Useful Information

1. What is the output of `vela --version`?

`v0.10.1`

2. What operating system is being used?

Linux

3. Any other important details?

N/A
