### ISSUE TITLE
bug: compiler causing panic for invalid regexp matchers

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#435]
## Description

providing a bad regexp pattern will cause the compiler to crash with a fatal panic.

caused by `regexp.MustCompile` 
https://github.com/go-vela/types/blob/b75a8b07bd293f7072934990334ffc0860dda957/pipeline/ruleset.go#L241

## Useful Information

step to reproduce:
```
steps:
  - name: bad_regex
    ruleset:
      matcher: regexp
      if:
        path:
          - "*foo.bar*"
```
