### ISSUE TITLE
Panic when pipeline contains nil step

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#450]
## Description

The server will currently return a panic when a pipeline like the following is processed:

```yaml
version: "1"

steps:
    - name: test
      image: alpine:latest
      commands:
        - echo hello
    -
```

This is caused by https://github.com/go-vela/types/blob/v0.11.0/yaml/step.go#L87 attempting to parse the value of nil step.

## Value

Server does not panic when an invalid pipeline is submitted.

1. What is the output of `vela --version`?

0.11.0

2. What operating system is being used?

linux
