### ISSUE TITLE
bug: comment event build restarted through UI loses context

### ISSUE THREAD

**Issue by davidvader** [go-vela/community#453]
## Description

a build triggered by a `comment` event containing some context that is restarted through the API will lose that context.

## Reproduce

trigger this build with a PR comment containing "content", then restart that build. the `comment-content` step will run in the initial build but not in the restarted build.

```yaml
version: "1"

steps:
- name: comment-content
  image: golang
  ruleset:
    event: comment
    comment: 'content'
  commands:
    - echo "comment contained 'content'"
```
