### ISSUE TITLE
Service that throws error with more than 500 characters doesn't update build state

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#468]
## Description

If you have a service container that is able to produce an error longer than 500 characters and exits, Vela will produce the following in the logs:
```text
"msg":"unable to upload final build state: unable to update build <org>/<repo>/<build number>: ERROR: value too lon
g for type character varying(500) (SQLSTATE 22001)"
```

The pipeline ends up in a perpetual `running` state with the `init` step completed and `clone` and `foo` steps skipped. The service will correctly show the `error` state. On the worker, the build _does_ stop and gets cleaned up, but the build state is never updated in the DB.

Pipeline to reproduce:
```yaml
version: "1"

services:
  - image: alpine:latest
    name: service that throws error
    pull: not_present
    entrypoint:
      - echo "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
      - exit 1

steps:
  - image: alpine:latest
    name: foo
    pull: not_present
    commands:
      - echo "bar"
```

The build state along with error message should properly get updated in the DB.

## Value

- Easier troubleshooting when this scenario is encountered. The error is not visible to the user currently.
- Build behaves as expected: build state is updated appropriately. 

## Useful Information

1. What is the output of `vela --version`?

`v0.11.0`

2. What operating system is being used?

3. Any other important details?
