### ISSUE TITLE
enhancement(vela-kaniko): expose the customPlatform parameter

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#477]
## Description

users can set [--customPlatform](https://github.com/GoogleContainerTools/kaniko#--customPlatform) to provide a platform flavor. we should expose that same functionality in the vela-kaniko wrapper

example yaml
```
version: "1"
steps:
  - name: docker_custom_platform
    image: docker.target.com/vela-plugins/kaniko:vHasCustomPlatform
    secrets: 
      - docker_username
      - docker_password
    parameters:
      custom_platform: "linux/arm/v5"
```
