### ISSUE TITLE
Provide a way to validate templates

### ISSUE THREAD

**Issue by colindean** [go-vela/community#511]
## Description

I have a repository of templates used in my repositories. I want to validate these templates; to have some kind of CI running a smoke test on them before allowing them to be merged into the default branch.

Normally, I could run `vela validate pipeline` as a pre-commit hook to validate that file locally to prevent a broken config from getting committed. 

If I wanted to simply validate the YAML of a template, I could run it through just about any YAML parser. However, because YAML templates have gotemplates in them, I can’t use just any YAML parser. 

Obviously, using Starlark would obviate this problem to a degree — I assume that Starlark has some kind of syntax checking validation mode — but I’d still want some validation for that but I suspect it already exists in a more generic way.

I tried using the built-in template validation, but it seems that the templates are only loaded and checked when referenced. I don't want to actually consume the templates this the templates repo config. 

See this example `.vela.yml` for the templates repo:

```yaml
version: "1"

templates:
  - name: docker
    source: git.example.com/myorg/vela-templates/docker.yml
    type: github
  - name: alerts
    source: git.example.com/vela-templates/alerts.yml
    type: github
  - name: build
    source: git.example.com/vela-templates/poetry-setup-unittest-staticchecks.yml
    type: github

steps:
  - name: validate templates
    image: alpine:3.15
    commands:
      - apk add curl tar gzip
      - curl -L https://github.com/go-vela/cli/releases/latest/download/vela_linux_amd64.tar.gz | tar zx
      - cp vela /usr/local/bin
      - |
        vela validate pipeline --template \
          --template-file docker:docker.yml \
          --template-file alerts:alerts.yml \
          --template-file build:poetry-setup-unittest-staticchecks.yml
```

The above passes event when docker.yml is modified in a way that isn't even valid YAML.

I also tried using [`gomplate`](https://docs.gomplate.ca) but it lacks at least the `default` function that Vela exposes as a part of integrating the `sprig` library extensions for gotemplates.

## Value

Validating at least the syntax of templates would prevent bad templates from breaking downstream pipelines.

## Definition of Done

The `vela` CLI tool can validate template files OR a Vela plugin exists that can validate all templates in a file glob or referenced in the config without invoking them.
