### ISSUE TITLE
environment section does not work

### ISSUE THREAD

**Issue by podollb** [go-vela/community#514]
this does not work:

```
environment:
  NAME: Ben

steps:

  - name: trying
    image: busybox:1.28
    commands:
      - "echo \"name: $NAME\""
```

this works:

```
environment:
  NAME: Ben

metadata:
  environment: [steps]

steps:

  - name: trying
    image: busybox:1.28
    commands:
      - "echo \"name: $NAME\""
```

docs say that by default `environment: [ steps, services, secrets ]` is set
