### ISSUE TITLE
Support client-driven rules in ruleset

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#524]
## Description

_ruleset_ could support more arbitrary rules to provide more flexibility in controlling which steps should run, in addition to the "environment-based" rules that are currently allowed.

Something like:

```yaml
steps:
  - name: deploy canary
    ruleset:
      test: ${DEPLOYMENT_PARAMETERS_HIGHLANDER}
      event: deploy
      target: [prod]
    vars:
      application: ${DEPLOYMENT_PARAMETERS_APPLICATION}

  - name: deploy app foo
    ruleset:
      event: deploy
      target: [prod]
      unless:
        test: ${DEPLOYMENT_PARAMETERS_HIGHLANDER

  - name: deploy app bar
    ruleset:
      event: deploy
      target: [prod]
      unless:
        test: ${DEPLOYMENT_PARAMETERS_HIGHLANDER}
```

or maybe something even more advanced

```yaml
steps:
  - name: deploy if true
    ruleset:
      predicate:
        param: ${DEPLOYMENT_PARAMETERS_SHOULD_DEPLOY}
        eq: true

  - name: deploy if doesn't exist
    ruleset:
      predicate:
        param: ${DEPLOYMENT_PARAMETERS_DO_NOT_DEPLOY}
        exists: false

  - name: deploy specific application
    ruleset:
      predicate:
        param: ${DEPLOYMENT_PARAMETERS_APPLICATION}
        eq: "myapplication"

  - name: deploy if any condition is met
    ruleset:
      predicate:
        param: ${DEPLOYMENT_PARAMETERS_APPLICATION}
        any:
          exists: false
          eq: "myapplication"

  - name: deploy if all conditions are met
    ruleset:
      predicate:
        param: ${DEPLOYMENT_PARAMETERS_APPLICATION}
        all:
          exists: true
          eq: "myapplication"

  - name: deploy if all conditions are met
    ruleset:
      all:
        - predicate:
          param: ${DEPLOYMENT_PARAMETERS_APPLICATION}
          exists: true
        - predicate:
          param: ${DEPLOYMENT_PARAMETERS_APPLICATION}
          eq: "myapplication"
```

_Not at all trying to dictate solutions but just wanted to throw out some examples._

## Value

We have several repos with multiple applications. With the current way we're doing things, the deployments are kind of all-or-nothing. We add a deployment, and all of the apps will deploy. Some other applications are single app repos, but we deploy multiple instances of the application. An example of one of these apps would be an application that has a dedicated cluster per warehouse.

What we would find useful is the ability to deploy to a single cluster to verify deployment/configuration changes, before "clicking the button" to deploy everywhere. Some of this is baked into shared templates and we can probably work around it, but the options I've come up with (utilizing what's currently available) are basically:

1. build this ability into a template where we can generate the correct steps depending on the parameters provided when the deploy was created.
2. override a concept like _target_ and give it more meaning. currently, _target_ is going to be something like _dev, stage, prod_ but we could in theory do something like add support for a value _canary_prod_ and then if we needed the "prod" part, we could parse it out.

I think that a general ability to flip on/off steps via deployment param would be useful though, and could potentially solve this problem for us in a relatively elegant way.
