### ISSUE TITLE
Reject pipelines with unknown top level fields

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#532]
## Description

A vela pipeline step generally takes this form:
```
  - name: publish
    image: alpine
    secrets: [ stuff]
    ruleset:
      branch: master
      event: push
    parameters:
      registry: docker.company.com
      repo: stuff
      tags: 'stuff'
```
The top level fields (image/secrets/ruleset/etc) are understood by vela and drive specific functionality. Everything else is baked into the `parameters` field, which gets passed to your image as environment variables.

It is possible that users add fields to the step itself that was intended to be a parameter (perhaps they copied an example from another CI tool). In which case, what they added would have no affect on anything.

## Value

Users might think they are configuring some specific behavior into their pipeline, but it would be ignored. For example, if they added the `dry_run: true` property to the root of their step instead of in parameters, they would be publishing/tagging a real docker image, which might be troublesome.
