### ISSUE TITLE
Anchors - Combine Lists

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#537]
## Description

In drone it wasn't possible to have a list in an anchor and add to that list in the actual step. 

In the example I have a secret field in the anchor but I can't add the `sonar_token` to that list in the actual build step. 

Example: 
```
build-image-anchor: &build-image-anchor
  image: docker.example.com/image/stuff
  secrets:
    - access_token
  environment:
    GRADLE_USER_HOME: .gradle
    GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Dorg.gradle.parallel=false

stages:
  build:
    steps:
      - name: build
        <<: *when-pull-request-or-merge-master
        <<: *build-image-anchor
        secrets:
          - sonar_token
        commands:
          - ./gradlew build
```

## Value

Increased reusability of anchors and a reduction in the duplication of code.
