### ISSUE TITLE
Ruleset to control the use of templates

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#547]
## Description

Control weather or not to use/run a template with a `ruleset`.

e.g.

```
steps:
  - name: a template to run on PR
    ruleset:
      event: pull_request
    template:
      name: some-template
      vars:
        some_var: abc
```

I would expect the above to only run steps in template on `pull_request`.

## Value

* can better control use of templates
