### ISSUE TITLE
Add support to use template with vault secret multiple times

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#550]
## Description

- we have a template which has vault secrets and takes template variables
- we include template once
- But we use it twice in same vela.yml for different purpose controlled by template variable, looks like vela is trying to create vault container multiple times with same name

## Value

Any template we are able to use multiple times in vela.yml, but when we add vault in template it fails and we need to do some workaround, which seems to be a drawback

**Comment by benzvan** [comment]
We're seeing a related issue that is basically the next step on this journey. We have multiple templates that use the same vault secrets. As a result, the vault container fetches the secrets multiple times. We've templated the name of the secret definition to avoid the collision.

I would propose pre-processing the secrets configuration and collapsing each of the secrets using a vault origin with the same authentication so that the vault secret plugin is called once with the complete list of (deduplicated) secrets.

**Comment by benzvan** [comment]
I think the way I would address this is to add an additional function in types/pipeline/secret.go that could be run after SecretSlice.Purge() like SecretSlice.MergeOrigins()

This function would inspect each Origin in the secret slice and determine if the source information is identical (Environment, Image, Pull, Secrets, and Parameters.username) and merge and dedupe the lists of secrets in Parameters.items into a single Origin. It could either generate a new name from the existing name or create something unique with an additional value to indicate where the secrets were merged from.

**Comment by GregoryDosh** [comment]
The scope of this issue is a little vague since I can think of two different issues it's trying to address. It could be trying to address the scope of name collisions of steps which are used in multiple templates or it could be to consolidate the number of times a plugin is expected to run.

If I focus on the second portion there for a moment, I don't think this is something the Vela server/worker/etc. should be doing. I don't think the pipeline should be enumerated and steps condensed FOR the user since the users should be able to manage their pipelines themselves. That is kind of going against making CI easy to reason with since the behavior changes depending on what sort of plugin or secrets you're pulling and too much magic makes debugging difficult.

Focusing on the specifics of being able to consolidate items being pulled from the Vault plugin, it would make more sense to update the vault plugin to give it the ability to take in parameters and configuration from a file path, and then update the documentation showing a more advanced use case where the plugin is pulled OUT of the top level secrets declaration and is instead part of a steps/stages block as a standalone step of pulling the secrets required.

Instead of...
```yaml
version: "1"

steps:
  ...

secrets:
  - name: VAULT_USERNAME
    key: SOME_ORG/VAULT_USERNAME
    engine: native
    type: org

  - name: VAULT_PASSWORD
    key: SOME_ORG/VAULT_PASSWORD
    engine: native
    type: org

  - origin:
      name: vault
      image: target/secret-vault:latest
      secrets: [ VAULT_USERNAME, VAULT_PASSWORD ]
      parameters:
        items:
          - source: secret/path/to/loc1
            path: loc1
          - source: secret/path/to/loc2
            path: loc2
```

You would have something more like...
```yaml
version: "1"

steps:
  - name: configure items 1
    image: alpine
    commands:
      - echo "source: secret/path/to/loc1,path: loc1" >> /vela/secrets/vault/items

  ...

  - name: configure items 2 (assume this came from a template)
    image: alpine
    commands:
      - echo "source: secret/path/to/loc2,path: loc2" >> /vela/secrets/vault/items

  - name: snag vault secrets
    image: target/secret-vault:latest
    secrets: [ VAULT_USERNAME, VAULT_PASSWORD ]

secrets:
  - name: VAULT_USERNAME
    key: SOME_ORG/VAULT_USERNAME
    engine: native
    type: org

  - name: VAULT_PASSWORD
    key: SOME_ORG/VAULT_PASSWORD
    engine: native
    type: org

```

**Comment by ecrupper** [comment]
Reading over this again after some new updates to the Vault plugin:

- https://github.com/go-vela/secret-vault/pull/458 (custom keys)
- https://github.com/go-vela/secret-vault/pull/438 (multiple paths)

Given those two implementations in combination with what @GregoryDosh said here:

> I don't think this is something the Vela server/worker/etc. should be doing. I don't think the pipeline should be enumerated and steps condensed FOR the user since the users should be able to manage their pipelines themselves.

I am going to close this issue as complete. Feel free to reopen if you want to discuss further.

**Comment by NickHackman** [comment]
Resurfaced this issue recently and just wanted to share a way to solve the problem of mounting the same template that contains the Vault plugin multiple times. Since the names have to be unique might as well leverage Sprig's UUID function

```yaml
secrets:
  - origin:
      name: vault_{{ uuidv4 }}
      image: vela-secrets/vault:v0.6.0
      secrets:
        - vault_username
        - vault_password
      parameters:
        addr: https://vault.com
        log_level: trace
        auth_method: ldap

```

Now this is really just a patch/hack to what @GregoryDosh mentioned as the core problem of templates being injected more than once
