### ISSUE TITLE
Status rule ignored when path rule specified

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#561]
## Description

Pipeline A
```yaml
version: '1'

steps:
  - name: failing step
    image: alpine:latest
    commands: 
      - exit 1
  
  - name: step that should work
    image: alpine:latest
    ruleset:
      status: [failure, success]
      path: somefile.txt
    commands:
      - echo hello
```
Pipeline B
```yaml
version: '1'

steps:
  - name: failing step
    image: alpine:latest
    commands: 
      - exit 1
  
  - name: step that should work
    image: alpine:latest
    ruleset:
      status: [failure, success]
    commands:
      - echo hello
```

Pipeline A will skip the second step as if the `status` rule that accepts both success and failure isn't there. Pipeline B works as expected. 

Result is the same for both `status: [failure]` and `status: [failure, success]`

## Value

Users should be able to specify a path and also the ability to continue regardless of build status.

## Useful Information

1. What is the output of `vela --version`?

`v0.12.0`
