### ISSUE TITLE
query docker registry for images before creating Pod

### ISSUE THREAD

**Issue by cognifloyd** [go-vela/community#579]
runtime/kubernetes/image.go CreateImage()

	// TODO: query docker registry for the image (if possible)
	//       this might require retrieving the pullSecrets from k8s
	// 		 or have the admin add a Vela accessible secret as well.

**Comment by cognifloyd** [comment]
For docker registry credentials (`authConfig` in my gist), kubernetes has a `kubernetes.io/dockerconfigjson` type `Secret` that is exactly what we need.
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

At first glance, mounting that secret as a file in the worker pod seems like just the thing to do.
https://stackoverflow.com/questions/56361831/how-to-mount-a-kubernetes-io-dockerconfigjson

But, that only works if: (1) the worker is running in kubernetes, and (2) the pipeline pods are in the same namespace as the worker.
The second assumption is not true for me, and we explicitly design the worker so it can do its thing from outside of kubernetes.

So, what about using the kubernetes client (`c.Kubernetes`) to retrieve the secret from the target namespace.

Whatever ServiceAccount Vela is using would need permission to do so:
```
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourcesNames: ["name-of-pull-secret"] // just the secret
  verbs: ["get"]
- apiGroups: [""]
  resources: ["serviceAcounts"]
  resourcesNames: ["name-of-service-account"] // just the service account.
  verbs: ["get"]
```

The kubernetes runtime should grab the secret that would be used to actually pull the image. So:
1. If the PipelinePodsTemplate has an ImagePullSecret, grab that
2. If the PipelinePodsTemplate specifies a ServiceAccount to use, then get that account's pull secret if any
3. If the default ServiceAccount has a pull secret, use that.
4. Try without authentication.
