### ISSUE TITLE
Replace "tags" with "keys" in docs

### ISSUE THREAD

**Issue by cognifloyd** [go-vela/community#599]
## Description

The way the docs talk about YAML is not quite right.

https://go-vela.github.io/docs/reference/yaml/#tags says:
> A YAML document is compose of one to many key-value pairs where the key is called the tag and the value is evaluated to an explicit type (Int, Float, string, bool, etc), see [YAML 1.2 spec for full details](https://yaml.org/spec/1.2/spec.html#id2761292).

In YAML, the "tag" defines the type. So, an explicitly tagged document looks like this:

```yaml
Block style: !!map
  Clark: !!str Evans
  Ingy: !!str döt Net
  Oren: !!str Ben-Kiki

Flow style: !!map { Clark: !!str Evans, Ingy: !!str döt Net, Oren: !!str Ben-Kiki }
```

Here, the tags are `!!map` and `!!str`. In practice, most YAML "tags" (which define data types) are implicit however, like this:

```yaml
Block style:
  Clark: Evans
  Ingy: döt Net
  Oren: Ben-Kiki

Flow style: { Clark: Evans, Ingy: döt Net, Oren: Ben-Kiki }
```

So, when the vela docs call these things "tags", that is unique to Vela - they are not "tags" elsewhere. It would be better to call them "keys". Here are some example keys that are called "tags" in the docs when "key" would be more appropriate:

- environment
- version
- metadata
    - template
    - clone
    - render_inline
- worker
    - flavor
    - platform
- templates
    - name
    - source
    - type
    - format
- services, steps
    - name
    - image
    - pull
    - secrets (step only)
    - environment
    - ruleset (step only)
    - parameters (step only)
    - commands (step only)
    - template (step only)
    - entrypoint
    - detach (step only)
    - ports (service only)
    - volume (step only)
    - ulimits
    - privileged (step only)
    - user
- stages
    - name
    - steps (hmm. Docs say this is type []string which is wrong)
    - needs
- secrets
    - name
    - key
    - engine
    - type
    - origin

When I started learning Vela, I was often confused by the use of "tags" in the Vela docs. it's taken a lot of effort to call stuff "tags" since that's what Vela seemed to call things. Then, I found that section of the docs that cites the YAML spec for calling things "tags". That was a misunderstanding of the spec, so I thought I'd raise this issue to clarify things.

## Value

Accuracy (uhm in a nit-picky way 😛)

## Definition of Done

Docs use the term "tag" correctly.

## Effort (Optional)

not much. Probably most effort will be discussing it in this issue.

## Impacted Personas (Optional)

docs users.
people.
me.
