### ISSUE TITLE
Tag not evaluated for ruleset on a deployment event

### ISSUE THREAD

**Issue by JayCeeJr** [go-vela/community#606]
## Description

Given the following ruleset, I would expect the deployment to be restricted to tags that match the pattern specified. However the step will be skipped because the tag is not evaluated on a deployment event.

```yaml
        ruleset:
          if:
            tag: [ release/* ]
            event: [ deployment ]
            target:
              - deploy-prod
```

## Value

A deployment can not be limited to a specific set of tags. I have to add an additional step to verify the tag on a deployment event and throw a non-zero exit code to accomplish this logic.

## Useful Information

Vela populates the tag on a deployment event, but does not evaluate it in the ruleset.
https://github.com/go-vela/types/blob/master/library/build.go#L160-L168
https://github.com/go-vela/worker/blob/master/internal/step/skip.go#L42-L52
