### ISSUE TITLE
v0.14 - pipelines create race condition

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#608]
## Description

pushing to a PR creates two events (`pull_request:synchronize` and `push`) which are both pointing to the same commit. it can cause the following error:

> ERROR: duplicate key value violates unique constraint \"pipelines_repo_id_commit_key\" (SQLSTATE 23505)

both events will query db for pipelines and neither will find one, so both go off and try to create one. only one will be able to do so.

redelivering the hook will work, but clearly not a great experience.

## Value

should expect the event to create a pipeline reliably.

## Useful Information

test pipeline:
```yaml
version: "1"

steps:
  - name: echo
    image: alpine:latest
    ruleset:
      event:
        - pull_request:synchronize
        - push
    commands:
      - echo hi there
```

1. What is the output of `vela --version`?

v0.14.0-rc2

2. What operating system is being used?

3. Any other important details?
