### ISSUE TITLE
Disallow pipeline from overwriting default environment variables

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#63]
## Description

A pipeline should be disallowed from overwriting any of the default environment variables. For example, the following pipeline will overwrite the `BUILD_AUTHOR` variable that vela defines internally:

```yaml
version: "1"

steps:
  - name: sample
    image: alpine:latest
    environment:
      BUILD_AUTHOR: "foo"
    commands:
      - env

```

## Value

Ensures plugins can accurately get information about the pipeline without fearing the pipeline is overwriting values.

## Useful Information

1. What is the output of `vela --version`?

Running the `latest` docker image of server and agent.

2. What operating system is being used?

Linux
