### ISSUE TITLE
Docker plugin labels parameter does not work

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#672]
## Description

ref: https://github.com/go-vela/vela-docker

the `labels` option does not pass custom labels to the CLI during the execution.

## Value
`labels` functionality should work as advertised

## Useful Information
example pipeline:
```yaml
version: "1"

steps:
  - name: docker example
    image: docker.target.com/vela-plugins/docker:latest
    pull: always
    parameters:
        registry: index.docker.io
        tags: [ index.docker.io/app/vela-test:latest ]
        dry_run: true
        labels:
           - HELLO=WORLD
```

the log output shows the default labels only.

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?
