### ISSUE TITLE
Support LFS in git plugin

### ISSUE THREAD

**Issue by colindean** [go-vela/community#673]
## Description

We're currently using this to pull down tags and LFS.

```starlark
def pull_git_tag_and_lfs(pull_tags_from_branch):
    return {
        "name": "git-lfs",
        "image": "hub.docker.target.com/gitlab/gitlab-runner:latest",
        "commands": [
            "git lfs pull",
            "git fetch --no-tags origin %s" % pull_tags_from_branch
        ]
    }
```

The git plugin can pull tags but it still can't pull LFS. 

## Value

Adding LFS would enable us to use the git plugin and not need to resort to external images.

## Definition of Done

Add `lfs: true` and it just works.

```yaml
steps:
  - name: clone_hello-world
    image: vela-plugins/git:v0.6.0
    pull: always
    parameters:
      path: hello-world
      ref: refs/heads/master
      remote: https://git.example.com/octocat/hello-world.git
      sha: 7fd1a60b01f91b314f59955a4e4d4e80d8edf11d
      tags: true
      lfs: true
```
