### ISSUE TITLE
Inline template fails to inject template_name variable

### ISSUE THREAD

**Issue by rfigueroa** [go-vela/community#675]
## Description

When a build uses an inline template, vela fails to inject the template_name variable
vela.yml
```yaml
---
version: "1"

metadata:
  template: false
  render_inline: true

templates:
  - name: inline_templatename
    source: github.example.com/github/octocat/template_name_template.yml
    type: github
```
template_name_template.yml
```yaml
metadata:
  template: true

steps:
  - name: hello
    image: {{ vela "template_name" }} #this will be emtpy
    commands:
      - echo {{ vela "template_name" }} ## this will print an empty value
```

## Value

Templates update the steps and stages names. Having the env var available will support inline templates with stages, as the template can have access to the final value of the rendered stage  name in the `needs:` tag

## Useful Information

1. What is the output of `vela --version`?

v0.14.0

2. What operating system is being used?

linux

3. Any other important details?
