### ISSUE TITLE
Add validation check for secrets in environment block

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#68]
## Description

We've seen several users of Vela attempt to reference a `secret` inside the `environment` block.

The typical use case for this is to "rename" the secret or in other words, inject the secret with a different name into the step.

An example:

```yaml
version: "1"

steps:
  - name: secret test
    image: alpine:latest
    secrets: [ foobar ]
    environment:
      PLUGIN_PARAMETER: ${FOOBAR}
    commands:
      - echo "boom"

secrets:
  - name: foobar
```

Vela already supports [a native injection method](https://go-vela.github.io/docs/concepts/pipeline/steps/secrets/#advanced) for "renaming" a secret for a step.

We should consider adding some type of validation check that will return an error if a user attempts to reference a secret in the `environment` block.

The error message could take multiple forms but as a sample:

> Vela doesn't allow injecting secrets under the environment block for security purposes.

## Value

* improve user experience with `secrets`

## Definition of Done

Vela returns an error message if a user attempts to reference a secret directly in the `environment` block.

## Effort  (Optional)

1 week

## Impacted Personas (Optional)

everyone
