### ISSUE TITLE
How do pull step images from a private registry

### ISSUE THREAD

**Issue by da6d6i7-bronga** [go-vela/community#685]
## Description
May be not a bug, or a doc bug.... lets talk about it.

We run in an air-gapped environment. Ideally, we need to pull our images from a private ACR, but in some cases, we can use our SaaS Artifactory. 

I am attempting to do this:

```
version: "1"
stages:
  install:
    steps:
      - name: install
        image: gapinc-docker-repo.jfrog.io/gradle:7.3.3-jdk11
        pull: always
        secrets: [ ARTIFACTORY_USERNAME, ARTIFACTORY_PASSWORD ]
        environment:
          GRADLE_USER_HOME: .gradle
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Dorg.gradle.parallel=false
        commands:
          - gradle downloadDependencies
```

But it's not liking it. I can pull this image using our Jenkins or the command line. The key part is that we need to authenticate.

I looked through several examples and the docs and could not find an answer. How can I get this to work?

## Value

Well, it's a way of life. Shift left and all.
