### ISSUE TITLE
Support conditional steps based on files in the workspace

### ISSUE THREAD

**Issue by Shamadeaus** [go-vela/community#689]
## Description

Allow for conditional steps in vela based files in the files in the vela workspace. For example if a step creates a file in the workspace the rest of the steps can operate based on if that file exists or not.
For example just like how `path` is based on files in the git diff, also support checking for the existence of a file in the workspace.
We mostly ran into the desire to do this for the slack plugin, but supporting within vela itself like `path` would be more flexible. 

## Value

Currently we have to write all of our vela steps with scripts that check for a file with bash.
if vela supported something like path for files in the workspace we could eliminate and simplify some of our scripts. As well as use the official slack plugin for our use case.

## Definition of Done
```
      - name: success-message
        <<: *slack-image
        ruleset:
          if:
            event: push
            workspace_file: [ .some_file ]
            <<: *on-merge
            status:
              - success
```
example maybe? open to more ideas

## Impacted Personas (Optional)

* Which personas will this impact? (i.e. users, admins etc.)
   Users writing pipelines will have more flexibility.
