### ISSUE TITLE
bug(vela-kaniko): build tag validation is failing when auto_tag is false 

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#701]
## Description

using the following pipeline
```
steps:
  - name: broke_autotag
    image: target/vela-kaniko
    pull: true
    ruleset:
      event: tag
      tag: "release/*"
    parameters:
      auto_tag: false
      tags:
        - latest
```

with a release using the tag string `anything/with/slash/3` will cause kaniko to fail validation, because the tag produced by github is not a valid "docker tag".
this should only happen when `auto_tag` is true, and the build tag is intended to be used as repo publish tag
