### ISSUE TITLE
Better tag resolution for deployments

### ISSUE THREAD

**Issue by zapplebee** [go-vela/community#705]
## Description

When creating a deployment, the ability to reference the tag associated with a commit should be a first class citizen of the tooling.

The pattern I want to enable is

1. Create a tag when an artifact should be stored long term (i.e. a semantic version of a docker image)
2. For deployments, be able to easily reference that a tag. (i.e. 
![image](https://user-images.githubusercontent.com/5760883/197668832-c6a92fd8-f481-4e9c-a7d4-2b6da3c81f94.png)
)

This is possible today, but it's messy and seems like a hack rather than a feature -- but it's an important pattern to enable for teams to easily semantically version their assets and, critically, decouple deployments from builds.

Generally speaking, every one of my .vela.yml files starts to look like this:

```yml
version: "1"

# Vela adds 'refs/heads/' to the front of the github deployment tag name, which is invalid
# This strips it back off so that git fetch can use either branches or tags
x-git-ref: &GITREF ${VELA_BUILD_REF/refs\/heads\//}

# by default, vela won't pull tags. we want it to so we can tag versions for deployment
# to higher environments. this metadata property prevents the default clone stage
# from happening, we later invoke a clone stage on our own

metadata:
  clone: false

stages:
  clone:
    steps:
      - name: clone
        image: target/vela-git
        parameters:
          tags: true
          ref: *GITREF

# ....
  build_image:
      #
      # docker build for api (publish the image)
      #
      - name: docker build on tag
        image:internal-corp-opinionated-docker-scaffold:3-stable
        ruleset:
          if:
            event: [tag]
        parameters:
          build_args:
            - BUILD_VERSION=${VELA_BUILD_TAG}
            - BUILD_LINK=${VELA_BUILD_LINK}
          dockerfile: ./Dockerfile.app
          repo: jollyroger
          tags:
            - ${VELA_BUILD_TAG}
          
 # ...
   deploy:
      - name: manual web
        ruleset:
          if:
            event: [deployment]
        image: internal-corp-opinionated-cd-scaffold/pirate:1-stable
        parameters:
          env: ${VELA_BUILD_TARGET}
          run_apply: true
          version: *GITREF         
```

## Value

Importantly, this makes tags and commits have parity when creating a deployment.

## Definition of Done

Would prefer that not all of my repositories need to have this boilerplate workaround code in order to deploy a tag.

## Effort  (Optional)

Unsure

## Impacted Personas (Optional)

Users and CI maintainers.
