### ISSUE TITLE
Automatically inject default variables into template

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#72]
## Description

[Templates](https://go-vela.github.io/docs/templates/overview/) should automatically have some of the default variables injected to reduce boilerplate variable injection that would otherwise be need.

### Current logic

template.yml

```yaml
metadata:
  template: true

{{$br := .branch}}

steps:

  - name: test
    commands:
      - go test ./...
    image: {{ .image }}
    {{ .pull_policy }}
    ruleset:
      event: [ push, pull_request ]

  # if branch equals master add this step to the final pipeline
  {{ if (eq $br "master") }}

  - name: build
    commands:
      - go build
    image: {{ .image }}
    {{ .pull_policy }}
    ruleset:
      event: [ push, pull_request ]

  {{ end }}
```

vela.yml

```yaml
version: "1"
templates:
  - name: sample
    source: github.com/<org>/<repo>/path/to/file/<template>.yml
    type: github

steps:
  - name: sample
    template:  
      name: golang
      vars:
        image: golang:latest
        pull_policy: "pull: true"
        branch: master
```

### Proposed logic

template.yml

```yaml
metadata:
  template: true

{{$br := getVelaBranch }}

steps:

  - name: test
    commands:
      - go test ./...
    image: {{ .image }}
    {{ .pull_policy }}
    ruleset:
      event: [ push, pull_request ]

  # if branch equals master add this step to the final pipeline
  {{ if (eq $br "master") }}

  - name: build
    commands:
      - go build
    image: {{ .image }}
    {{ .pull_policy }}
    ruleset:
      event: [ push, pull_request ]

  {{ end }}
```

vela.yml

```yaml
version: "1"
templates:
  - name: sample
    source: github.com/<org>/<repo>/path/to/file/<template>.yml
    type: github

steps:
  - name: sample
    template:  
      name: golang
      vars:
        image: golang:latest
        pull_policy: "pull: true"
```

Mixed opinions if this should utilize custom [functions](https://golang.org/pkg/text/template/#hdr-Functions) or if we merge the vars and system vars together.

## Value

- Reduce the boilerplate variable injection needed
- Templates can ensure that variable values are consistent/correct

## Definition of Done

Templates are able to determine information about the pipeline without needing to inject vars

## Effort  (Optional)

couple of days

## Impacted Personas (Optional)

Anyone that utilizes templates
