### ISSUE TITLE
bug (vela-github-release): files parameter doesn't seem to accept a glob

### ISSUE THREAD

**Issue by colindean** [go-vela/community#724]
## Description

When I use the vela-github-release plugin, I expect to be able to pass a glob to match many files instead of having to list all files.

```yaml
- name: Release to GitHub on every Main Push
  image:  target/vela-github-release:latest
  secrets:
    - source: github_token
      target: CONFIG_TOKEN
  parameters:
    action: create
    files: [ "*.pdf" ]
    target: main
  ruleset:
    branch: [main]
    event: [push]

```

This seemed to be passed to `gh` correctly, but it didn't work:

```
{
  "canonical": "v0.2.0",
  "major": 0,
  "minor": 2,
  "patch": 0,
  "metadata": {
    "architecture": "amd64",
    "build_date": "2022-08-22T16:03:50Z",
    "compiler": "gc",
    "git_commit": "e21c0d9178cc7cca132cb1c2f2cabc54182cc2be",
    "go_version": "go1.18.5",
    "operating_system": "linux"
  }
}
[36mINFO   [0m[0000] Vela Github Release Plugin                    [36mcode[0m="https://github.com/go-vela/vela-github-release" [36mdocs[0m="https://go-vela.github.io/docs/plugins/registry/github-release/" [36mregistry[0m="https://hub.docker.com/r/target/vela-github-release"
$ /bin/gh version
gh version 2.14.4 (2022-08-10)
https://github.com/cli/cli/releases/tag/v2.14.4
$ /bin/gh auth login --hostname=git.mycompany.com --with-token
$ /bin/gh release create 2022.11.17.20
 *.pdf --draft=false --prerelease=false --target=main --title=v2022.11.17.20

stat *.pdf: no such file or directory
exit status 1
```

My workaround is 

```yaml
- make list-outputs > /vela/parameters/github-release/files
```

which just writes the expected outputs to that file, which the GH Release plugin reads when the `files` parameter isn't passed.

## Value

I'd expect globs to work in file specs because it's a pretty standard feature. It seems like it _should_ be working but it's not. I speculate that `gh` might be relying on shell-level glob behavior instead of expanding the glob itself. The plugin would then be passing a string `*.pdf` as a parameter instead of the shell expanding it and passing the names of the PDF files in its place.

## Useful Information

1. What is the output of `vela --version`?

See metadata above.

2. What operating system is being used?

See metadata above.

3. Any other important details?

No.
