### ISSUE TITLE
operator if/or causing false positive steps to compile

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#74]
## Description

When using `ruleset` an `if` with an `operator: or` will cause some rules to be ignored or create false positives, leading to the incorrect steps being ran.

*.vela.yml to reproduce*
```
version: "1"
steps:
  - name: echo
    image: golang
    ruleset:
      if:
        branch: master
        event: pull_request
      operator: or
    commands:
      - echo "hello"
```
*steps to reproduce*
push to `dev`

## Value

complex rulesets do not function correctly

## Useful Information

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?

**Comment by rmknecht** [comment]
Our team is also experiencing this bug. The following ruleset results in two _duplicate_ builds when pushing to an open PR.

```
ruleset:
  if:
    branch: master
    event: pull_request
  operator: or
  ```

Is there a ruleset for pushing to master -or- opening/pushing to a PR, that eliminates the unnecessary build?
