### ISSUE TITLE
plugin: default branch change for vela-git

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#816]
## Description

In the `0.18.x` release of Vela, the version of [go-vela/vela-git](https://github.com/go-vela/vela-git) was upgraded from `0.5.1` to `0.7.0`:

https://github.com/go-vela/server/pull/755

The `v0.7.0` version of that plugin introduced an undocumented, breaking change:

https://github.com/go-vela/vela-git/pull/122

Prior to this change, the branch setup from that plugin was always set to `master`.

Now, that branch will be set to whatever the default branch is in the SCM for that repo.

> NOTE: I understand the reasoning behind this change, but it should be documented as a breaking change.

To demonstrate this, first setup a `.vela.yml` that looks like this:

```yaml
version: "1"

steps:
  - name: demo
    image: alpine:latest
    commands:
      - apk add git
      - git branch
      - git status
```

Assuming the default branch in the SCM for the repo is set to `main`, you'll see output like:

```
<other output>
$ git branch
* main
$ git status
On branch main
nothing to commit, working tree clean
```

After that, update the `.vela.yml` to invoke the old plugin:

```yaml
version: "1"

metadata:
  clone: false

steps:
  - name: clone
    image: target/vela-git:v0.6.0

  - name: demo
    image: alpine:latest
    commands:
      - apk add git
      - git branch
      - git status
```

Regardless of what the default branch in the SCM for the repo is set to, you'll see it say `master`:

```
<other output>
$ git branch
* master
$ git status
On branch master
nothing to commit, working tree clean
```

This can break processes that were dependent on the old setup i.e. Sonarqube

## Value

Document the breaking changes so others are aware of the impact.

## Useful Information

1. What is the output of `vela --version`?

https://github.com/go-vela/ui/releases/tag/v0.19.0
https://github.com/go-vela/server/releases/tag/v0.18.2
https://github.com/go-vela/worker/releases/tag/v0.18.1

2. What operating system is being used?

https://www.flatcar.org/

3. Any other important details?

N/A

**Comment by jbrockopp** [comment]
After some trial and error, I was able to leverage `v0.7.0` successfully using the `default_branch` parameter:

```yaml
version: "1"

metadata:
  clone: false

steps:
  - name: clone
    image: target/vela-git:v0.7.0
    parameters:
      default_branch: ${VELA_PULL_REQUEST_SOURCE}
```

The branch checked out by Vela's `clone` step will point to the repo's default branch configured in the SCM.

I believe this behavior is a bug since it doesn't follow expected behavior.

To explain my line of thinking further:

* I create a repo with a default branch of `main` that has my source code
* I open a PR from branch `foo` to modify code that targets my default branch (`main`)
* Vela clones the source code from `foo` but incorrectly sets the branch as `main`
* PR analysis processes get confused since the current branch (`main`) matches the PR target branch (`main`)

Instead, Vela should clone the source code from `foo` and set the branch as `foo` so processes that do PR analysis (i.e. Sonarqube) don't get confused about the current branch (`foo`) matching the PR target branch (`main`).
