### ISSUE TITLE
npm plugin: skip publish step if version already exists in npm 

### ISSUE THREAD

**Issue by nicklpeterson** [go-vela/community#827]
## Description

My team is using the npm plugin to publish a package within a mono-repo. The package should not be published every time there is a merge to main, instead we only want to publish the package if there was a merge to main and the version increased in the package.json. Would it be feasible to add a parameter that indicates the plugin should only attempt to push if the version doesn't already exist in npm?

Something like this:

```yml
stages:
  deploy package:
    steps:
      - name: build
         <<: [ *image-node, *ruleset-push ]
         commands:
           - yarn package:build
      - name: publish
         <<: [ *image-npm-plugin, *ruleset-push ]
         parameters:
            <<: *params-npm-publish
            skip_if_version_exists: true
```

Also happy to hear suggestions if there is already a good way to do this in vela.

## Value

This would make the plugin more flexible for use in mono-repos where we don't want to attempt to publish packages without a version change.

## Definition of Done

The vela npm plugin has a parameter that skips the build if the version number already exists in npm.

## Effort  (Optional)

Not quite sure. There is a command `npm view <pkg> version` that can be used to check if the version exists. So, I believe we would need to parse the version number from the package.json file and then call that npm command.
