### ISSUE TITLE
fix: update repo counter with missing template

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#899]
## Description

We had a user attempt to trigger the first build on a new repo in Vela with the following pipeline:

```yaml
# For more details on templates, see the vela docs:
# https://go-vela.github.io/docs/templates/
# https://go-vela.github.io/docs/reference/yaml/templates/
# https://go-vela.github.io/docs/templates/tutorials/go/
# use the @branch-name override when testing
# templates:
#   - name: example
#     source: .vela.template.yml
#     type: file

stages:
  demo:
    steps:
      - name: demo
        template:
          name: example
``` 

> NOTE: The `demo` step isn't valid because the `example` template is commented out.

So, when Vela went to create the build for the pipeline in the system, it led to this error shown on the `Builds` page:

<img width="652" alt="image" src="https://github.com/go-vela/community/assets/10966923/3f6fecc3-d7ce-4c17-840f-35f371c7c10a">

> NOTE: This error message is a bit misleading since a `template` is involved but that is a different problem.

The actual bug is that Vela didn't update the repo `counter` for this build leading to a broken state.

Without admin intervention, subsequent commits to the repo show this error on the `Audit` page:

<img width="1337" alt="image" src="https://github.com/go-vela/community/assets/10966923/551bce9e-682a-4d31-b403-342f4ded5a3a">

This is because the counter is stuck at `0` for the repo while the actual number of builds for the repo is `1`.

The workaround is to manually update the counter on the `Settings` page from `0` -> `1`.

## Value

A repo doesn't end up in a broken state that requires a repo or platform admin to resolve

## Useful Information

1. What is the output of `vela --version`?

`v0.20.3`

2. What operating system is being used?

https://www.flatcar.org/

3. Any other important details?

N/A
