### ISSUE TITLE
Develop a `status` ruleset for an independent stage

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#910]
## Description

Example pipeline:
```yaml
version: "1"

stages:
  failing:
    steps:
      - name: fail
        image: alpine:latest
        commands:
          - exit 1

  indy:
    independent: true
    steps:
      - name: wait
        image: alpine:latest
        commands:
          - sleep 5

      - name: should not run
        image: alpine:latest
        ruleset:
          status: failure
        commands:
          - echo "why am I running"
```

The above will execute the `should not run` step because the overall build's status is a failure. This issue suggests we should either change the logic for the `status` ruleset for independent stages OR create a new status like `stage-failure` or something along those lines.

## Value

It more accurately aligns with the "spirit" of independent stages.

## Definition of Done

There is a way where the example pipeline above does not execute that `should not run` step.

## Effort  (Optional)

1-2 weeks maybe
