### ISSUE TITLE
`vela validate pipeline` does not work with file type templates without local replace

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#916]
## Description

Example pipeline:

```yaml
version: "1"

templates:
  - name: push_branch
    source: vela-templates/push_branch.yml
    type: file

steps:
 - name: push_branch
    ruleset:
      if:
        event: push
      unless:
        branch: main
    template: 
      name: push_branch
```

Resulting command:
```sh
$ vela validate pipeline
FATA[0000] no Vela template found at //vela-templates/push_branch.yml 
```

It seems to be some pathing issue with how we read in templates that are of file type when executing locally. 

## Value

Saves users from having to local replace, e.g. `vela validate pipeline --template-file push_branch:vela-templates/push_branch.yml`

1. What is the output of `vela --version`?

`v0.23.0`

2. What operating system is being used?

3. Any other important details?
