### ISSUE TITLE
Pull Request status is updated on `edited` action, overwriting previous state

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#958]
## Description

Steps to reproduce:

```yaml
version: "1"

steps:
  - name: title validator
    image: alpine:latest
    report_as: title-validator
    ruleset:
      event: [ pull_request:opened, pull_request:reopened, pull_request:edited ]
    commands:
      - echo $VELA_BUILD_MESSAGE | grep -Eq '^(feat|fix|chore|refactor|enhance|test|docs)(\(.*\)|):\s.+$' && (echo "Pass"; exit 0) || (echo "Incorrect Format"; exit 1)

  - name: test step
    image: alpine:latest
    ruleset:
      event: [ pull_request ] # translates to pull_request:opened, pull_request:synchronize, pull_request:reopened
    commands:
      - exit 1
```

If you submit a PR with this pipeline, it will fail the `test step` and update the status to say it failed. However, you can update the title to be the correct format and the `pull request` status will now become successful. 

## Value

This isn't ideal, as it can cause teams to miss failing statuses.

## Useful Information

This only occurs when the repo has `pull_request:edited` events enabled. It might be useful to also explain that `edited` is not the same as `synchronize`. It's a bit confusing for users I would think.

1. What is the output of `vela --version`?

`v0.23.3`

2. What operating system is being used?

3. Any other important details?

Dipping into solution talk here, I think the best approach forward would be to _not_ report status for the non-standard PR actions. Rather, we could report specific steps that run during those builds.
