### ISSUE TITLE
Artifactory Plugin - Update docs to show proper regex usage

### ISSUE THREAD

**Issue by wass3rw3rk** [go-vela/community#979]
## Description

The artifactory plugin claims to have functionality to define a regexp pattern for the sources for an upload action. Using a step such as:
```yaml
name: upload_artifacts_date
image: target/vela-artifactory
ruleset:
  event: push
secrets: [artifactory_username, artifactory_password]
parameters:
  action: upload
  log_level: trace
  path: some/path/here/
  regexp: true
  sources:
    - file_\d{4}-\d{2}-\d{2}.yml
  url: https://artifactory.example.com
```

results in an error such as:

```
[Error] path does not exist: file_\d{4}-\d{2}-\d{2}.yml
[Error] path does not exist: file_\d{4}-\d{2}-\d{2}.yml
time="2024-05-29T15:07:06Z" level=fatal msg="path does not exist: file_\\d{4}-\\d{2}-\\d{2}.yml"
```

Note: the double error of "path does not exist" is how it shows up.

## Value

The plugin should work as advertised

## Useful Information

Adding a simple test case to the upload test here https://github.com/go-vela/vela-artifactory/blob/main/cmd/vela-artifactory/upload_test.go will confirm the issue.

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?
