### ISSUE TITLE
server: support per-step timeout

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#982]
## Description

support for per-step level timeouts would be helpful. 

something like
```yaml
steps:
  - name: download-dependencies
    timeout: 30m
    commands:
      - ...do something that might timeout
```
