### ISSUE TITLE
worker/server: support for env_file step parameter

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#983]
## Description

support for shared env file step source would be cool

```yaml
steps:
  - name: write-env
    commands:
      - echo "fFOO=bar" >> $VELA_BUILD_WORKSPACE/.env-new
  - name: use-env
    env_file: .env-new
    commands:
      - echo $FOO
```
