### ISSUE TITLE
server: restarted pull_request labeled builds missing steps

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#993]
see title, use the following yaml, trigger a build, restart it. build will be missing the labeled step

```yaml
  - name: pull-labeled-with-bug
    image: golang
    ruleset:
      event: 'pull_request:labeled'
      label: [ 'bug' ]
    commands:
      - echo "pull request labeled"

  - name: run-always
    image: golang
    commands:
      - echo "why did the step prior to this skip"
```

**Comment by ecrupper** [comment]
This extends to comment steps with additional `comment` specification, e.g.

```yaml
  - name: comment-with-bug
    image: golang
    ruleset:
      event: comment
      comment: :"test suite"
    commands:
      - echo "running comment-driven test suite"

  - name: run-always
    image: golang
    commands:
      - echo "run always"
```
